driver:
  name: docker
  use_sudo: false

verifier:
  name: inspec

platforms:
  - name: centos-7.4

suites:
  - name: vault
    driver:
      hostname: vault
      instance_name: vault
      forward:
        - 8200:8200
    provisioner:
      name: shell
      script: 'test/smoke/vault-helper/bootstrap.sh'
      arguments: [
        '--sudo',
        '--hab-version=0.79.1',
        '--hab-sup-start',
        '--hab-bldr-url=https://bldr.habitat.sh',
        '--hab-pkgs=core/jq-static',
        '--hab-services=smoke/vault-helper/vault-services.json',
        '--hab-binlink'
      ]
      data_path: 'test'

  - name: vault-helper
    driver:
      links:
        - "vault:vault"
      hostname: vault-helper
      instance_name: vault-helper
    provisioner:
      name: shell
      script: 'test/smoke/vault-helper/bootstrap.sh'
      arguments: [
        '--sudo',
        '--vault-node=vault',
        '--hab-version=0.79.1',
        '--hab-sup-start',
        '--hab-peer=vault',
        '--hab-bldr-url=https://bldr.habitat.sh',
        '--hab-pkgs=core/jq-static',
        '--hab-harts=*.hart',
        '--hab-binlink'
      ]
      data_path: 'results'
    verifier:
      inspec_tests:
        - test/smoke/vault-helper
